"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import publicapi_versionresponse as shared_publicapi_versionresponse
from typing import Optional



@dataclasses.dataclass
class APIServerVersionResponse:
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    api_server_version_400_application_json_string: Optional[str] = dataclasses.field(default=None)
    r"""Bad Request"""
    api_server_version_500_application_json_string: Optional[str] = dataclasses.field(default=None)
    r"""Internal Server Error"""
    publicapi_version_response: Optional[shared_publicapi_versionresponse.PublicapiVersionResponse] = dataclasses.field(default=None)
    r"""OK"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    

