"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from typing import Optional



@dataclasses.dataclass
class APIServerDebugResponse:
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    api_server_debug_200_application_json_string: Optional[str] = dataclasses.field(default=None)
    r"""OK"""
    api_server_debug_500_application_json_string: Optional[str] = dataclasses.field(default=None)
    r"""Internal Server Error"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    

