"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import healthinfo as shared_healthinfo
from typing import Optional



@dataclasses.dataclass
class GetHealthzResponse:
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    health_info: Optional[shared_healthinfo.HealthInfo] = dataclasses.field(default=None)
    r"""OK"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    

