"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import types_healthinfo as shared_types_healthinfo
from typing import Optional



@dataclasses.dataclass
class HealthzResponse:
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    types_health_info: Optional[shared_types_healthinfo.TypesHealthInfo] = dataclasses.field(default=None)
    r"""OK"""
    

