"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from typing import Optional



@dataclasses.dataclass
class IDResponse:
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    id_200_text_plain_string: Optional[str] = dataclasses.field(default=None)
    r"""OK"""
    id_500_text_plain_string: Optional[str] = dataclasses.field(default=None)
    r"""Internal Server Error"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    

