"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import peer_addrinfo as shared_peer_addrinfo
from typing import Optional



@dataclasses.dataclass
class PeersResponse:
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    peer_addr_infos: Optional[list[shared_peer_addrinfo.PeerAddrInfo]] = dataclasses.field(default=None)
    r"""OK"""
    peers_500_application_json_string: Optional[str] = dataclasses.field(default=None)
    r"""Internal Server Error"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    

