"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import publicapi_stateresponse as shared_publicapi_stateresponse
from typing import Optional



@dataclasses.dataclass
class PkgRequesterPublicapiStatesResponse:
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    pkg_requester_publicapi_states_400_application_json_string: Optional[str] = dataclasses.field(default=None)
    r"""Bad Request"""
    pkg_requester_publicapi_states_500_application_json_string: Optional[str] = dataclasses.field(default=None)
    r"""Internal Server Error"""
    publicapi_state_response: Optional[shared_publicapi_stateresponse.PublicapiStateResponse] = dataclasses.field(default=None)
    r"""OK"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    

