"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import publicapi_listresponse as shared_publicapi_listresponse
from typing import Optional



@dataclasses.dataclass
class PkgRequesterPublicapiListResponse:
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    pkg_requester_publicapi_list_400_application_json_string: Optional[str] = dataclasses.field(default=None)
    r"""Bad Request"""
    pkg_requester_publicapi_list_500_application_json_string: Optional[str] = dataclasses.field(default=None)
    r"""Internal Server Error"""
    publicapi_list_response: Optional[shared_publicapi_listresponse.PublicapiListResponse] = dataclasses.field(default=None)
    r"""OK"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    

