"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import publicapi_cancelresponse as shared_publicapi_cancelresponse
from typing import Optional



@dataclasses.dataclass
class PkgRequesterPublicapiCancelResponse:
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    pkg_requester_publicapi_cancel_400_application_json_string: Optional[str] = dataclasses.field(default=None)
    r"""Bad Request"""
    pkg_requester_publicapi_cancel_401_application_json_string: Optional[str] = dataclasses.field(default=None)
    r"""Unauthorized"""
    pkg_requester_publicapi_cancel_403_application_json_string: Optional[str] = dataclasses.field(default=None)
    r"""Forbidden"""
    pkg_requester_publicapi_cancel_500_application_json_string: Optional[str] = dataclasses.field(default=None)
    r"""Internal Server Error"""
    publicapi_cancel_response: Optional[shared_publicapi_cancelresponse.PublicapiCancelResponse] = dataclasses.field(default=None)
    r"""OK"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    

