"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import publicapi_eventsresponse as shared_publicapi_eventsresponse
from typing import Optional



@dataclasses.dataclass
class PkgRequesterPublicapiEventsResponse:
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    pkg_requester_publicapi_events_400_application_json_string: Optional[str] = dataclasses.field(default=None)
    r"""Bad Request"""
    pkg_requester_publicapi_events_500_application_json_string: Optional[str] = dataclasses.field(default=None)
    r"""Internal Server Error"""
    publicapi_events_response: Optional[shared_publicapi_eventsresponse.PublicapiEventsResponse] = dataclasses.field(default=None)
    r"""OK"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    

