"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class Engine(int, Enum):
    ENGINE_UNKNOWN = 0
    ENGINE_NOOP = 1
    ENGINE_DOCKER = 2
    ENGINE_WASM = 3
    ENGINE_DONE = 4
