"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class ExecutionDesiredState(int, Enum):
    EXECUTION_DESIRED_STATE_PENDING = 0
    EXECUTION_DESIRED_STATE_RUNNING = 1
    EXECUTION_DESIRED_STATE_STOPPED = 2
