"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ..shared import spec as shared_spec
from bac import utils
from dataclasses_json import Undefined, dataclass_json


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class JobCreatePayload:
    api_version: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('APIVersion') }})
    client_id: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('ClientID') }})
    r"""the id of the client that is submitting the job"""
    spec: shared_spec.Spec = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('Spec') }})
    r"""The specification of this job."""
    

