"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class JobHistoryType(int, Enum):
    JOB_HISTORY_TYPE_UNDEFINED = 0
    JOB_HISTORY_TYPE_JOB_LEVEL = 1
    JOB_HISTORY_TYPE_EXECUTION_LEVEL = 2
