"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from bac import utils
from dataclasses_json import Undefined, dataclass_json
from typing import Optional


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class JobRequester:
    requester_node_id: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('RequesterNodeID'), 'exclude': lambda f: f is None }})
    r"""The ID of the requester node that owns this job."""
    requester_public_key: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('RequesterPublicKey'), 'exclude': lambda f: f is None }})
    r"""The public key of the Requester node that created this job
    This can be used to encrypt messages back to the creator
    """
    

