"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class Network(int, Enum):
    NETWORK_NONE = 0
    NETWORK_FULL = 1
    NETWORK_HTTP = 2
