"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class NodeType(int, Enum):
    NODE_TYPE_REQUESTER = 0
    NODE_TYPE_COMPUTE = 1
