"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class StorageSourceType(int, Enum):
    STORAGE_SOURCE_UNKNOWN = 0
    STORAGE_SOURCE_IPFS = 1
    STORAGE_SOURCE_REPO_CLONE = 2
    STORAGE_SOURCE_REPO_CLONE_LFS = 3
    STORAGE_SOURCE_URL_DOWNLOAD = 4
    STORAGE_SOURCE_ESTUARY = 5
    STORAGE_SOURCE_INLINE = 6
    STORAGE_SOURCE_LOCAL_DIRECTORY = 7
    STORAGE_SOURCE_S3 = 8
    STORAGE_SOURCE_DONE = 9
