"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import badrequest as shared_badrequest
from ..shared import internalservererror as shared_internalservererror
from ..shared import stateresponse as shared_stateresponse
from typing import Optional



@dataclasses.dataclass
class GetStatesResponse:
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    bad_request: Optional[shared_badrequest.BadRequest] = dataclasses.field(default=None)
    r"""Bad Request"""
    internal_server_error: Optional[shared_internalservererror.InternalServerError] = dataclasses.field(default=None)
    r"""Internal Server Error"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    state_response: Optional[shared_stateresponse.StateResponse] = dataclasses.field(default=None)
    r"""OK"""
    

