"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ..shared import model_engine as shared_model_engine
from ..shared import model_publisher as shared_model_publisher
from ..shared import model_resourceusagedata as shared_model_resourceusagedata
from ..shared import model_storagesourcetype as shared_model_storagesourcetype
from dataclasses_json import Undefined, dataclass_json
from test_bac import utils
from typing import Optional


@dataclass_json(undefined=Undefined.EXCLUDE)

@dataclasses.dataclass
class ModelComputeNodeInfo:
    available_capacity: Optional[shared_model_resourceusagedata.ModelResourceUsageData] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('AvailableCapacity'), 'exclude': lambda f: f is None }})
    enqueued_executions: Optional[int] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('EnqueuedExecutions'), 'exclude': lambda f: f is None }})
    execution_engines: Optional[list[shared_model_engine.ModelEngine]] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('ExecutionEngines'), 'exclude': lambda f: f is None }})
    max_capacity: Optional[shared_model_resourceusagedata.ModelResourceUsageData] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('MaxCapacity'), 'exclude': lambda f: f is None }})
    max_job_requirements: Optional[shared_model_resourceusagedata.ModelResourceUsageData] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('MaxJobRequirements'), 'exclude': lambda f: f is None }})
    publishers: Optional[list[shared_model_publisher.ModelPublisher]] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('Publishers'), 'exclude': lambda f: f is None }})
    running_executions: Optional[int] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('RunningExecutions'), 'exclude': lambda f: f is None }})
    storage_sources: Optional[list[shared_model_storagesourcetype.ModelStorageSourceType]] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('StorageSources'), 'exclude': lambda f: f is None }})
    

